---
Name: EmbedShortcodeProviderFullScreen
---

SilverStripe\Core\Injector\Injector:
  SilverStripe\View\Shortcodes\EmbedShortcodeProvider:
    class: Sunnysideup\FullScreenTinyMceVideoEmbed\View\ShortCodes\EmbedShortcodeProviderFullScreen
